import { Router } from "express";
import userRoutes from "./user.routes";
import authRoutes from "./auth.routes";
import serviceRoutes from "./service.routes";
import roleRoutes from "./role.routes";
import permissionRoutes from "./permission.routes";
import customerRoutes from "./customer.routes";
import bookingRoutes from "./booking.routes";
import staffRoutes from "./staff.routes";
import appointmentRoutes from "./appointment.routes";
import invoiceRoutes from "./invoice.routes";
import productRoutes from "./product.routes";
import settingsRoutes from "./settings.routes";
import loyaltyRoutes from "./loyalty.routes";

const router = Router();
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/service", serviceRoutes);
router.use("/role", roleRoutes);
router.use("/permission", permissionRoutes);
router.use("/customer", customerRoutes);
router.use("/booking", bookingRoutes);
router.use("/staff", staffRoutes);
router.use("/appointment", appointmentRoutes);
router.use("/invoice", invoiceRoutes);
router.use("/product", productRoutes);
router.use("/settings", settingsRoutes);
router.use("/loyalty", loyaltyRoutes);
export default router;
