export const APPOINTMENTS = {
  list: {
    description: 'Day, week, and month calendar.',
    add: 'New appointment',
    emptyStaff: 'Add active staff to see the day calendar.',
    closedDay: 'Closed',
    viewDay: 'Day',
    viewWeek: 'Week',
    viewMonth: 'Month',
    today: 'Today',
    prev: 'Previous',
    next: 'Next',
    selectedTitle: 'Selected appointment',
    emptySlot: 'No appointment selected',
    emptySlotHint: 'Click a booking or an empty slot to get started.',
    viewOnlyPast: 'Past appointment, view only',
    viewOnlyStatus: 'This appointment is {status} and cannot be changed.',
  },
  form: {
    createTitle: 'New appointment',
    editTitle: 'Edit appointment',
    viewTitle: 'Appointment details',
    viewOnlyBanner: 'View only — this appointment cannot be edited.',
    back: 'Appointments',
    sectionContact: '1. Contact details',
    sectionServices: '2. Service details',
    sectionNotes: '3. Appointment notes',
    schedule: 'Schedule',
    pricing: 'Pricing',
    customer: 'Customer',
    guest: 'Walk-in guest',
    guestName: 'Guest name',
    guestPhone: 'Phone',
    emailOptional: 'Email (optional)',
    date: 'Date',
    startTime: 'Start time',
    endTime: 'End time',
    duration: 'Duration',
    services: 'Services',
    assignStaff: 'Staff',
    addService: 'Add service',
    notes: 'Notes',
    notesPlaceholder: 'Anything the stylist should know…',
    priceTotal: 'Estimated total',
    save: 'Save appointment',
    cancel: 'Cancel',
    estimatedMinutes: 'min',
  },
  detail: {
    collectPayment: 'Create bill',
    cancel: 'Cancel appointment',
    markNoShow: 'Mark no-show',
    edit: 'Edit appointment',
    phone: 'Phone',
    services: 'Services',
    timeSlot: 'Time',
    price: 'Price',
    staff: 'Staff',
    notes: 'Notes',
  },
  confirm: {
    createdTitle: 'Appointment confirmed!',
    updatedTitle: 'Appointment updated',
    cancelledTitle: 'Appointment cancelled',
    billedTitle: 'Bill created',
    subtitle: 'Here is a quick summary of the booking.',
    summary: 'Appointment summary',
    print: 'Print details',
    sendWhatsApp: 'Send confirmation to client',
    close: 'Close',
    customer: 'Customer',
    phone: 'Phone',
    services: 'Services',
    staff: 'Staff',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    total: 'Total',
    whatsappTemplate:
      'Hi {customer}, your appointment at {salon} is on {date} at {time} for {services}. See you soon!',
  },
  status: {
    booked: 'Booked',
    completed: 'Completed',
    cancelled: 'Cancelled',
    no_show: 'No-show',
  },
  toasts: {
    created: 'Appointment booked',
    updated: 'Appointment updated',
    cancelled: 'Appointment cancelled',
    outsideHours: 'The salon is closed at this time.',
    statusUpdated: 'Status updated',
  },
  errors: {
    loadFailed: 'Could not load appointments',
  },
} as const
