export const AUTH = {
  loginTitle: 'Sign in',
  identifier: 'Email or username',
  identifierPlaceholder: 'you@salon.com or username',
  password: 'Password',
  passwordPlaceholder: 'Your password',
  submit: 'Sign in',
  submitting: 'Signing in…',
  failed: 'Could not sign in',
  forgotHint: 'Forgot your password? Ask your admin to reset it.',
  setPassword: {
    title: 'Set a new password',
    description: 'You must choose a new password before continuing.',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    submit: 'Save and continue',
    mismatch: 'Passwords do not match',
    sameAsTemp: 'New password must be different from the temporary password',
  },
  account: {
    title: 'Account',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    savePassword: 'Update password',
    changeEmail: 'Change email',
    newEmail: 'New email',
    saveEmail: 'Update email',
    passwordUpdated: 'Password updated',
    emailUpdated: 'Email updated',
  },
} as const
