export const BILLING = {
  list: {
    description: "Today's bills and walk-in checkouts.",
    newBill: 'New bill',
    emptyTitle: 'No bills yet',
    emptyHint: 'Start a walk-in bill or collect payment from an appointment.',
    searchPlaceholder: 'Search invoice or customer',
  },
  new: {
    description: 'Add services and products, then checkout.',
    backToBills: 'Back to bills',
    fromAppointment: 'From appointment',
    customer: 'Customer',
    walkIn: 'Walk-in',
    addCustomer: 'Add new customer',
    searchCustomer: 'Search by name, phone, or ID',
    phonePrefix: '+91',
    selectedCustomer: 'Selected customer',
    loyaltyBalance: 'Loyalty balance',
    lastVisit: 'Last visit',
    addItems: 'Add items',
    service: 'Service',
    product: 'Product',
    addService: 'Add service',
    addProduct: 'Add product',
    searchItem: 'Type to search…',
    searchService: 'Search services…',
    searchProduct: 'Search products…',
    doneBy: 'Done by',
    soldBy: 'Sold by',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    discount: 'Disc.',
    lineTotal: 'Line total',
    servicesHeading: 'Services',
    productsHeading: 'Products',
    sectionDiscounts: 'Discounts',
    servicesDiscount: 'Services discount',
    productsDiscount: 'Products discount',
    notes: 'Notes',
    notesPlaceholder: 'Optional note for this bill',
    summaryTitle: 'Billing summary',
    gross: 'Gross',
    discountLabel: 'Discount',
    discountAmount: 'Discount amount',
    net: 'Net',
    emptyServices: 'No services on this bill yet.',
    emptyProducts: 'No products on this bill yet.',
    cgst: 'CGST',
    sgst: 'SGST',
    loyaltyRedeem: 'Loyalty redemption',
    redeemPoints: 'Redeem points',
    useMax: 'Use max',
    availablePoints: 'Available',
    roundOff: 'Round off',
    tip: 'Tip',
    tipFor: 'Tip for',
    noTip: 'No tip',
    customTip: 'Custom',
    grandTotal: 'Grand total',
    subtotal: 'Subtotal',
    payable: 'Payable amount',
    paymentMode: 'Payment mode',
    amountReceived: 'Amount received',
    changeToReturn: 'Change to return',
    checkout: 'Checkout',
    reset: 'Reset',
    saving: 'Saving…',
    needLines: 'Add at least one service or product.',
    needStaff: 'Assign staff on every line.',
    assignStaff: 'Assign staff',
    clearCart: 'Clear cart',
    percent: '%',
    amount: '₹',
  },
  invoice: {
    description: 'Paid invoice details.',
    newBill: 'New bill',
    print: 'Print',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'Share on WhatsApp',
    revokeLink: 'Revoke link',
    backToBills: 'Back to bills',
    whatsappDownloaded:
      'PDF downloaded. Attach it in WhatsApp if the link is not enough.',
    walkInPhoneTitle: 'Customer phone for WhatsApp',
    walkInPhoneHint: 'Enter a mobile number with country code, or 10 digits for India.',
    walkInPhoneLabel: 'Phone number',
    walkInPhoneContinue: 'Continue',
    invalidPhone: 'Enter a valid phone number',
    shareFailed: 'Could not prepare WhatsApp share',
    pdfUnavailable: 'Could not create the PDF. Try Print → Save as PDF instead.',
    linkRevoked: 'Public link revoked',
  },
  toasts: {
    created: 'Payment collected',
    createFailed: 'Could not save bill',
    staffRequired: 'Assign staff on every line',
    paymentRequired: 'Choose a payment mode',
  },
} as const
