export const BILLING = {
  list: {
    description: "Today's bills and walk-in checkouts.",
    newBill: 'New bill',
    emptyTitle: 'No bills yet',
    emptyHint: 'Start a walk-in bill or collect payment from an appointment.',
    searchPlaceholder: 'Search invoice or customer',
  },
  new: {
    title: 'New bill',
    description: 'Add services and products, then checkout.',
    draftSubtitle: 'Draft · {when}',
    backToBills: 'Back to bills',
    fromAppointment: 'From appointment',
    saveDraft: 'Save draft',
    printEstimate: 'Print estimate',
    draftsMenu: 'Drafts ({count})',
    draftsEmpty: 'No saved drafts',
    resumeDraft: 'Resume',
    deleteDraft: 'Delete draft',
    draftSaved: 'Draft saved',
    estimateTitle: 'Estimate',
    estimateDisclaimer: 'Estimate, not a tax invoice',
    estimateNoNumber: 'No invoice number',
    customerCardTitle: '1 · Customer',
    customer: 'Customer',
    walkIn: 'Walk-in',
    appointmentMode: 'Appointment',
    addCustomer: 'Add new customer',
    searchCustomer: 'Search by name or phone',
    phonePrefix: '+91',
    selectedCustomer: 'Selected customer',
    loyaltyBalance: 'Loyalty balance',
    lastVisit: 'Last visit',
    returningClient: 'Returning client',
    newClient: 'New client',
    bookedAt: 'Booked {time}',
    changeCustomer: 'Change',
    pickAppointment: 'Select a booked appointment',
    noAppointmentsToday: 'No booked appointments today.',
    freeName: 'Name',
    freePhone: 'Phone',
    addItemsCardTitle: '2 · Add services & products',
    addItems: 'Add items',
    service: 'Service',
    product: 'Product',
    servicesTab: 'Services',
    productsTab: 'Products',
    addService: 'Add service',
    addProduct: 'Add product',
    searchItem: 'Type to search…',
    searchService: 'Search services…',
    searchProduct: 'Search products…',
    quickAdd: 'Quick add',
    showAll: 'Show all',
    showLess: 'Show less',
    billItemsTitle: '3 · Bill items ({count})',
    itemAndStylist: 'Item & stylist',
    stylist: 'Stylist',
    doneBy: 'Done by',
    soldBy: 'Sold by',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    lineDiscount: 'Line discount',
    net: 'Net',
    total: 'Total',
    discount: 'Disc.',
    lineTotal: 'Line total',
    noDiscount: 'No discount',
    discountOff: '−{amount} off',
    emptyBillItems: 'Add a service to start',
    servicesHeading: 'Services',
    productsHeading: 'Products',
    servicesCount: 'Services ({count})',
    productsCount: 'Products ({count})',
    sectionDiscounts: 'Discounts',
    servicesDiscount: 'Services discount',
    productsDiscount: 'Products discount',
    notes: 'Notes',
    notesPlaceholder: 'Optional note for this bill',
    summaryTitle: 'Bill summary',
    gross: 'Gross',
    discountLabel: 'Total discount',
    discountAmount: 'Discount amount',
    taxable: 'Taxable',
    emptyServices: 'No services on this bill yet.',
    emptyProducts: 'No products on this bill yet.',
    moreFromCategory: 'More from {category}',
    showAllInCategory: 'Show all',
    decreaseQty: 'Decrease quantity',
    increaseQty: 'Increase quantity',
    cgst: 'CGST',
    sgst: 'SGST',
    cgstRate: 'CGST ({rate}%)',
    sgstRate: 'SGST ({rate}%)',
    loyaltyRedeem: 'Loyalty',
    redeemPoints: 'Redeem points',
    useMax: 'Use max',
    availablePoints: 'Available',
    roundOff: 'Round off',
    tip: 'Tip',
    tipFor: 'Tip for',
    noTip: 'None',
    customTip: 'Custom',
    tipGoesTo: 'Goes to {name}',
    tipSplitEqually: 'Split equally: {names} ({amount} each)',
    tipAssignEmpty: 'Add items to assign the tip',
    tipShare: '{name}: {amount}',
    grandTotal: 'Grand total',
    subtotal: 'Subtotal',
    payable: 'Payable',
    paymentMode: 'Payment mode',
    amountReceived: 'Amount received',
    changeToReturn: 'Change to return',
    collectVia: 'Collect {amount} via {mode}',
    checkout: 'Checkout',
    reset: 'Reset',
    saving: 'Saving…',
    needLines: 'Add at least one service or product.',
    needStaff: 'Assign staff on every line.',
    assignStaff: 'Assign staff',
    clearCart: 'Clear cart',
    percent: '%',
    amount: '₹',
    badgeService: 'Service',
    badgeProduct: 'Product',
    qtyTimes: '{name} × {qty}',
    lineStaff: '{staff}',
  },
  invoice: {
    description: 'Paid invoice details.',
    newBill: 'New bill',
    print: 'Print',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'Share on WhatsApp',
    revokeLink: 'Revoke link',
    backToBills: 'Back to bills',
    whatsappDownloaded:
      'PDF downloaded. Attach it in WhatsApp if the link is not enough.',
    walkInPhoneTitle: 'Customer phone for WhatsApp',
    walkInPhoneHint: 'Enter a mobile number with country code, or 10 digits for India.',
    walkInPhoneLabel: 'Phone number',
    walkInPhoneContinue: 'Continue',
    invalidPhone: 'Enter a valid phone number',
    shareFailed: 'Could not prepare WhatsApp share',
    pdfUnavailable: 'Could not create the PDF. Try Print → Save as PDF instead.',
    linkRevoked: 'Public link revoked',
  },
  toasts: {
    created: 'Payment collected',
    createFailed: 'Could not save bill',
    staffRequired: 'Assign staff on every line',
    paymentRequired: 'Choose a payment mode',
  },
} as const
