export const COMMON = {
  appName: 'BeautySalon',
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    close: 'Close',
    back: 'Back',
    retry: 'Retry',
    search: 'Search',
    clear: 'Clear',
    reset: 'Reset',
    confirm: 'Confirm',
    exportCsv: 'Export CSV',
    print: 'Print',
    copy: 'Copy',
    more: 'More',
    signOut: 'Sign out',
    viewAll: 'View all',
    apply: 'Apply',
    remove: 'Remove',
    import: 'Import',
    next: 'Next',
    previous: 'Previous',
  },
  labels: {
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    gender: 'Gender',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    notes: 'Notes',
    date: 'Date',
    time: 'Time',
    total: 'Total',
    subtotal: 'Subtotal',
    optional: 'Optional',
    required: 'Required',
    loading: 'Loading…',
    today: 'Today',
    actions: 'Actions',
    yes: 'Yes',
    no: 'No',
  },
  empty: {
    generic: 'Nothing here yet',
    genericHint: 'Add an item to get started.',
    noResults: 'No results found',
    noResultsHint: 'Try a different search.',
  },
  errors: {
    loadFailed: 'Could not load data',
    saveFailed: 'Could not save',
    deleteFailed: 'Could not delete',
    unexpected: 'Something went wrong',
    noAccess: 'You do not have access to this page',
    noAccessHint: 'Ask an admin if you need permission.',
    notFound: 'Page not found',
    notFoundHint: 'That screen does not exist.',
    goHome: 'Go to dashboard',
  },
  toasts: {
    saved: 'Saved',
    deleted: 'Deleted',
    copied: 'Copied',
  },
  nav: {
    dashboard: 'Dashboard',
    appointments: 'Appointments',
    customers: 'Customers',
    billing: 'Billing',
    staff: 'Team & Staff',
    services: 'Services',
    products: 'Products',
    loyalty: 'Loyalty',
    reports: 'Reports',
    salesReport: 'Sales report',
    profitReport: 'Profit report',
    settings: 'Settings',
    account: 'Account',
    groupGeneral: 'General',
    groupFinance: 'Finance',
    groupManagement: 'Management',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    searchPlaceholder: 'Search client or invoice',
    searchEmpty: 'No matching clients or invoices',
    searchClients: 'Clients',
    searchInvoices: 'Invoices',
    newBill: 'New bill',
    newAppointment: 'New appointment',
    addCustomer: 'Add customer',
    todayCalendar: "Today's appointments",
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    moreMenu: 'More',
  },
  gender: {
    Male: 'Male',
    Female: 'Female',
    Other: 'Other',
  },
  paymentMode: {
    cash: 'Cash',
    upi: 'UPI',
    card: 'Card',
  },
} as const
