export const CUSTOMERS = {
  list: {
    description: 'Customer directory and history.',
    add: 'Add customer',
    emptyTitle: 'No customers yet',
    emptyHint: 'Add a customer or create one from billing.',
    searchPlaceholder: 'Search name or phone',
  },
  detail: {
    description: 'Profile, visits, and loyalty.',
    edit: 'Edit customer',
    loyaltyPoints: 'Loyalty points',
    lifetimeSpend: 'Lifetime spend',
    visits: 'Visits',
    visitHistory: 'Visit history',
    emptyVisits: 'No visits yet',
    emptyVisitsHint: 'Bills collected for this customer will show here.',
    loadVisitsFailed: 'Could not load visits',
    colDate: 'Date',
    colServices: 'Services',
    colInvoice: 'Invoice',
    colTotal: 'Total',
    profile: 'Profile',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    notFound: 'Customer not found',
    back: 'Back',
  },
  form: {
    createTitle: 'Add customer',
    editTitle: 'Edit customer',
    name: 'First name',
    lastName: 'Last name',
    phone: 'Phone',
    gender: 'Gender',
  },
  toasts: {
    created: 'Customer added',
    updated: 'Customer updated',
    deleted: 'Customer removed',
  },
} as const
