export const DASHBOARD = {
  title: 'Dashboard',
  description: "Today's collection, appointments, and staff performance.",
  loadFailed: 'Dashboard failed to load',
  rangeToday: 'Today',
  rangeWeek: 'This week',
  rangeMonth: 'This month',
  activeClients: 'Active clients',
  activeClientsHint: 'Visited in the last 30 days',
  appointmentsToday: "Today's appointments",
  walkIns: 'walk-ins',
  revenue: 'Revenue',
  collectionToday: 'Collection today',
  tipsLine: 'Tips',
  viewAll: 'View all',
  revenueStatistics: 'Revenue statistics',
  servicesLegend: 'Services',
  productsLegend: 'Products',
  topPerformers: 'Top performers',
  todaysProgress: "Today's progress",
  appointmentsCompleted: 'appointments completed',
  recentCustomers: 'Recent customers',
  lastVisit: 'Last visit',
  visits: 'visits',
  points: 'pts',
  emptyAppointments: 'No appointments scheduled for today.',
  emptyTrend: 'No sales recorded this year yet.',
  emptyStaff: 'No staff sales in this period yet.',
  emptyCustomers: 'No recent customer visits yet.',
  vsPrior: 'vs prior',
  cash: 'Cash',
  upi: 'UPI',
  card: 'Card',
} as const
