export const INVENTORY = {
  list: {
    description: 'Retail and consumable products with optional stock.',
    add: 'Add product',
    import: 'Import',
    emptyTitle: 'No products yet',
    emptyHint: 'Add products sold at the counter or used in the salon.',
    searchPlaceholder: 'Search products',
    filterAll: 'All',
    filterRetail: 'Retail',
    filterConsumable: 'Consumable',
    colType: 'Type',
    colStock: 'Stock',
    colUnit: 'Unit',
    badgeInStock: 'In stock',
    badgeOutOfStock: 'Out of stock',
    badgeNotTracked: 'Not tracked',
    typeRetail: 'Retail',
    typeConsumable: 'Consumable',
  },
  detail: {
    description: 'Product details.',
    edit: 'Edit product',
  },
  form: {
    createTitle: 'Add product',
    editTitle: 'Edit product',
    description: 'Name, type, price, and optional stock tracking.',
    name: 'Name',
    price: 'Price',
    type: 'Type',
    unit: 'Unit',
    unitPlaceholder: 'e.g. pcs, ml, bottle',
    trackStock: 'Track stock',
    openingStock: 'Opening stock',
  },
  stock: {
    add: 'Add stock',
    use: 'Use stock',
    adjust: 'Adjust',
    history: 'History',
    quantity: 'Quantity',
    countedQty: 'Counted quantity',
    reason: 'Reason',
    note: 'Note',
    optionalNote: 'Optional note',
    reasonRequired: 'Reason is required',
    historyTitle: 'Stock history',
    colDate: 'Date',
    colType: 'Type',
    colQty: 'Qty',
    colBalance: 'Balance',
    colReason: 'Reason',
    colUser: 'User',
    colInvoice: 'Invoice',
  },
  toasts: {
    created: 'Product added',
    updated: 'Product updated',
    deleted: 'Product removed',
    stockUpdated: 'Stock updated',
    stockFailed: 'Could not update stock',
  },
} as const
