export const REPORTS = {
  hub: {
    description: 'Key numbers and reports for sales, team, customers, and operations.',
    keyNumbers: 'Key numbers',
    revenue: 'Revenue',
    avgBill: 'Average bill',
    newCustomers: 'New customers',
    noShowRate: 'No-show rate',
    groups: {
      sales: 'Sales',
      team: 'Team',
      customers: 'Customers',
      operations: 'Operations',
    },
    cards: {
      sales: {
        title: 'Sales summary',
        description: 'Revenue, bills, tips, and payment mix for the period.',
      },
      staff: {
        title: 'Staff performance',
        description: 'Who sold what — services, products, and tickets.',
      },
      customers: {
        title: 'Customer report',
        description: 'Top spenders, inactive clients, and walk-in share.',
      },
      appointments: {
        title: 'Appointment report',
        description: 'Booking status, busy hours, and bill conversion.',
      },
      services: {
        title: 'Service report',
        description: 'Best sellers, not sold, and discount effect.',
      },
      products: {
        title: 'Product report',
        description: 'Retail sales and who sold the most units.',
      },
    },
    backToReports: 'Back to reports',
  },
  shared: {
    emptyBills: 'No bills in this period',
    emptyHint: 'Try a different date range.',
    dash: '—',
    howCalculated: {
      title: 'How calculated',
      bullets: [
        'Revenue = amount payable minus tip (tax included as stored on the invoice).',
        'Tips are tracked separately and excluded from revenue.',
        'Change % compares an equal number of days immediately before this range.',
        'Valid invoices include all statuses (there is no void status yet).',
      ],
    },
    export: 'Export CSV',
    searchPlaceholder: 'Search…',
    pageOf: '{page} / {total}',
    rowsTotal: '{total} rows',
  },
  presets: {
    today: 'Today',
    yesterday: 'Yesterday',
    sevenDays: '7 days',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    custom: 'Custom',
    from: 'From',
    to: 'To',
    apply: 'Apply',
  },
  sales: {
    title: 'Sales summary',
    description: 'Revenue, bills, tips, and payment mix for the period.',
    emptyTitle: 'No bills in this period',
    emptyHint: 'Collect payments to see sales here.',
    kpis: {
      revenue: 'Revenue',
      bills: 'Bills',
      avgBill: 'Average bill',
      tips: 'Tips',
    },
    chart: {
      title: 'Revenue trend',
      total: 'Total',
      services: 'Services',
      products: 'Products',
    },
    splits: {
      services: 'Service sales',
      products: 'Product sales',
      paymentModes: 'Payment modes',
    },
    table: {
      title: 'Bills',
      invoice: 'Invoice',
      date: 'Date',
      customer: 'Customer',
      items: 'Items',
      revenue: 'Revenue',
      tip: 'Tip',
      payment: 'Payment',
      status: 'Status',
    },
    searchPlaceholder: 'Search invoice or customer',
  },
  staff: {
    title: 'Staff performance',
    description: 'Who sold what — services, products, and tickets.',
    emptyTitle: 'No staff sales in this period',
    emptyHint: 'Sales appear after checkout with staff assigned.',
    kpis: {
      totalSales: 'Total sales',
      topPerformer: 'Top performer',
      servicesDone: 'Services done',
      averageTicket: 'Average ticket',
    },
    chart: {
      title: 'Sales by staff',
    },
    table: {
      rank: 'Rank',
      staff: 'Staff',
      servicesDone: 'Services done',
      serviceSales: 'Service sales',
      productSales: 'Product sales',
      totalSales: 'Total sales',
      averageTicket: 'Avg ticket',
      salesChange: 'Change',
      expand: 'Line items',
      collapse: 'Hide lines',
      type: 'Type',
      item: 'Item',
      qty: 'Qty',
      attributed: 'Attributed',
      invoice: 'Invoice',
      date: 'Date',
    },
  },
  customers: {
    title: 'Customer report',
    description: 'Top spenders, inactive clients, and walk-in share.',
    emptyTitle: 'No customers in this period',
    emptyHint: 'Bills linked to customers will appear here.',
    kpis: {
      newCustomers: 'New customers',
      returning: 'Returning',
      averageSpend: 'Average spend',
      averageVisits: 'Average visits',
      walkInBills: 'Walk-in bills',
    },
    chart: {
      title: 'New vs returning',
      newLabel: 'New',
      returningLabel: 'Returning',
    },
    tabs: {
      top: 'Top customers',
      inactive: 'Inactive',
    },
    filters: {
      inactiveDays: 'Inactive for',
      days30: '30 days',
      days60: '60 days',
      days90: '90 days',
    },
    table: {
      name: 'Customer',
      phone: 'Phone',
      spend: 'Spend',
      visits: 'Visits',
      averageTicket: 'Avg ticket',
      lastVisit: 'Last visit',
      loyaltyPoints: 'Points',
      daysSinceVisit: 'Days since visit',
      whatsapp: 'WhatsApp',
    },
    whatsappTemplate:
      'Hi {customer}, we miss you at {salon}. Book a visit when you are ready!',
    inactiveEmptyTitle: 'No inactive customers',
    inactiveEmptyHint: 'Everyone has visited recently.',
  },
  appointments: {
    title: 'Appointment report',
    description: 'Booking status, busy hours, and bill conversion.',
    emptyTitle: 'No appointments in this period',
    emptyHint: 'Bookings in this range will show here.',
    kpis: {
      total: 'Total',
      completed: 'Completed',
      noShowRate: 'No-show rate',
      cancellationRate: 'Cancel rate',
      bookingToBill: 'Booking → bill',
    },
    chart: {
      statusTitle: 'By status',
      busyTitle: 'Busy hours',
      walkInTitle: 'Walk-in vs appointment bills',
      walkIn: 'Walk-in',
      appointment: 'Appointment',
      count: 'Count',
    },
    filters: {
      status: 'Status',
      allStatuses: 'All statuses',
      staff: 'Staff',
      allStaff: 'All staff',
    },
    days: {
      sun: 'Sun',
      mon: 'Mon',
      tue: 'Tue',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
    },
    table: {
      date: 'Date',
      time: 'Time',
      status: 'Status',
      customer: 'Customer',
      staff: 'Staff',
      services: 'Services',
      billed: 'Billed',
    },
  },
  services: {
    title: 'Service report',
    description: 'Best sellers, not sold, and discount effect.',
    emptyTitle: 'No service sales in this period',
    emptyHint: 'Completed bills with services will appear here.',
    kpis: {
      soldCount: 'Times sold',
      revenue: 'Revenue',
      distinctCount: 'Distinct services',
      avgDiscountPct: 'Avg discount %',
    },
    chart: {
      title: 'Top 10',
      byRevenue: 'By revenue',
      byCount: 'By count',
    },
    filters: {
      category: 'Category',
      allCategories: 'All categories',
      notSold: 'Not sold in period',
    },
    table: {
      name: 'Service',
      category: 'Category',
      timesSold: 'Times sold',
      revenue: 'Revenue',
      listPrice: 'List price',
      avgPriceCharged: 'Avg charged',
      discountPctEffect: 'Discount %',
      revenueShare: 'Share %',
    },
  },
  products: {
    title: 'Product report',
    description: 'Retail sales and who sold the most units.',
    emptyTitle: 'No product sales in this period',
    emptyHint: 'Retail lines on bills will appear here.',
    kpis: {
      soldCount: 'Units sold',
      revenue: 'Revenue',
      distinctCount: 'Distinct products',
      avgDiscountPct: 'Avg discount %',
    },
    chart: {
      title: 'Top 10',
      byRevenue: 'By revenue',
      byCount: 'By count',
    },
    staffTable: {
      title: 'Product sales per staff',
      staff: 'Staff',
      units: 'Units',
      revenue: 'Revenue',
    },
    table: {
      name: 'Product',
      timesSold: 'Times sold',
      revenue: 'Revenue',
      listPrice: 'List price',
      avgPriceCharged: 'Avg charged',
      discountPctEffect: 'Discount %',
      revenueShare: 'Share %',
      topSeller: 'Top seller',
    },
  },
} as const
