export const ROUTES = {
  login: '/login',
  home: '/',
  appointments: '/appointments',
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  billing: '/billing',
  billingNew: '/billing/new',
  invoice: (id: string) => `/billing/${id}`,
  publicInvoice: (token: string) => `/i/${token}`,
  staff: '/staff',
  staffDetail: (id: string) => `/staff/${id}`,
  services: '/services',
  inventory: '/inventory',
  productDetail: (id: string) => `/inventory/${id}`,
  loyalty: '/loyalty',
  settings: '/settings',
  settingsSection: (section: string) => `/settings/${section}`,
  reports: '/reports',
  reportsSales: '/reports/sales',
  reportsStaff: '/reports/staff',
  reportsInventory: '/reports/inventory',
  reportsProfit: '/reports/profit',
  forbidden: '/forbidden',
  setPassword: '/set-password',
  account: '/account',
} as const
