export const SERVICES = {
  list: {
    description: 'Service menu with duration and price.',
    add: 'Add service',
    import: 'Import',
    emptyTitle: 'No services yet',
    emptyHint: 'Add services or import from a spreadsheet.',
    searchPlaceholder: 'Search services',
    tabServices: 'Services',
    tabCategories: 'Categories',
    tabCombos: 'Combos',
    allCategories: 'All categories',
  },
  form: {
    createTitle: 'Add service',
    editTitle: 'Edit service',
    description: 'Name, category, price, and how long the service takes.',
    name: 'Name',
    category: 'Category',
    categoryPlaceholder: 'Select a category',
    createCategoryOption: '+ Create new category',
    price: 'Price',
    duration: 'Duration (minutes)',
  },
  categories: {
    title: 'Categories',
    description: 'Manage service categories used on the menu and in billing.',
    add: 'Add category',
    emptyTitle: 'No categories yet',
    emptyHint: 'Create a category or import services with a category column.',
    name: 'Name',
    services: 'Services',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    rename: 'Rename',
    deactivate: 'Deactivate',
    activate: 'Activate',
    createTitle: 'New category',
    createDescription: 'Categories group services on the menu and in suggestions.',
    namePlaceholder: 'e.g. Hair',
    nameRequired: 'Category name is required',
    toasts: {
      created: 'Category added',
      updated: 'Category updated',
      createFailed: 'Could not add category',
      updateFailed: 'Could not update category',
    },
  },
  combos: {
    title: 'Combos',
    description: 'Package multiple services at a combo price.',
    add: 'Add combo',
    emptyTitle: 'No combos yet',
    emptyHint: 'Create a combo with at least two services.',
    name: 'Name',
    included: 'Included services',
    listTotal: 'List total',
    comboPrice: 'Combo price',
    saving: 'Saving',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    deactivate: 'Deactivate',
    activate: 'Activate',
    delete: 'Delete',
    formCreateTitle: 'Add combo',
    formEditTitle: 'Edit combo',
    formDescription: 'Pick services and set the package price.',
    services: 'Services',
    servicesPlaceholder: 'Select services',
    price: 'Combo price (₹)',
    confirmAboveList:
      'Combo price is not below the list total. Save anyway?',
    confirmAboveListAction: 'Save anyway',
    duration: 'Duration',
    toasts: {
      created: 'Combo added',
      updated: 'Combo updated',
      deleted: 'Combo removed',
      createFailed: 'Could not add combo',
      updateFailed: 'Could not update combo',
      deleteFailed: 'Could not remove combo',
    },
  },
  toasts: {
    created: 'Service added',
    updated: 'Service updated',
    deleted: 'Service removed',
    imported: 'Import finished',
  },
} as const
