export const SETTINGS = {
  description:
    'Configure how your salon looks on bills, when you are open, and who can do what.',
  hubTitle: 'Settings',
  backToSettings: 'Settings',
  leaveUnsaved:
    'You have unsaved changes. Leave this page without saving?',
  unsavedHint: 'Unsaved changes',
  allSaved: 'All changes saved',
  saving: 'Saving…',
  sections: {
    business: 'Business profile',
    tax: 'Tax',
    invoice: 'Invoice',
    appointments: 'Appointment slots',
    loyalty: 'Loyalty',
    roles: 'Roles & permissions',
    /** @deprecated use roles */
    designations: 'Roles & permissions',
  },
  sectionDescriptions: {
    business: 'Salon name, address, GSTIN, opening hours',
    tax: 'GST rates for services and products',
    invoice: 'Numbering, templates, and print options',
    appointments: 'Slot size, notice window, and booking days',
    loyalty: 'Earn and redeem rules for customers',
    roles: 'Staff designations and permission matrix',
  },
  business: {
    salonName: 'Salon name',
    logo: 'Logo',
    uploadLogo: 'Upload logo',
    removeLogo: 'Remove logo',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    phone: 'Phone',
    email: 'Email',
    gstin: 'GSTIN',
    footerNote: 'Invoice footer note',
    openingTime: 'Opening time',
    closingTime: 'Closing time',
    workingDays: 'Working days',
    weeklyOff: 'Weekly off',
    save: 'Save business profile',
  },
  tax: {
    gstEnabled: 'GST enabled',
    pricesIncludeGst: 'Prices include GST',
    servicesCgst: 'Services CGST %',
    servicesSgst: 'Services SGST %',
    productsCgst: 'Products CGST %',
    productsSgst: 'Products SGST %',
    save: 'Save tax settings',
  },
  invoice: {
    prefix: 'Invoice prefix',
    includeYear: 'Include year',
    padding: 'Number padding',
    nextNumber: 'Next number',
    rounding: 'Rounding',
    template: 'Template',
    save: 'Save invoice settings',
    title: 'Invoice',
    titleUpper: 'INVOICE',
    invoiceFrom: 'Invoice from',
    invoiceTo: 'Invoice to',
    numberLabel: 'Invoice number',
    colDescription: 'Description',
    colQty: 'Qty',
    colRate: 'Rate',
    colAmount: 'Amount',
    taxable: 'Taxable value',
    termsTitle: 'Terms & conditions',
    termsDefault:
      'Goods once sold will not be taken back. Please retain this invoice for your records.',
    paymentMethod: 'Payment method',
    accentColor: 'Accent color',
    accentPreset: 'Accent preset',
    customAccent: 'Custom accent',
    showStaffNames: 'Show staff names on lines',
    showLogo: 'Show logo on invoice',
    termsText: 'Terms & conditions',
    thankYouText: 'Thank-you message',
    thankYouDefault:
      'Thank you for visiting. We look forward to seeing you again.',
    whatsappMessage: 'WhatsApp message',
    whatsappDefault:
      'Hi {customer}, here is your invoice from {salon} for {amount}. View: {link}',
    whatsappHint:
      'Placeholders: {customer} {salon} {amount} {link}',
    whatsappExample: 'Example',
    shareLinkDays: 'Public link expiry (days)',
    customerFallback: 'Customer',
    templates: {
      creamGold: 'Cream & Gold',
      blush: 'Blush',
      compact: 'Compact A5',
      thermal: 'Thermal',
    },
    accents: {
      gold: 'Gold',
      blush: 'Blush',
      teal: 'Teal',
      charcoal: 'Charcoal',
      sage: 'Sage',
      plum: 'Plum',
      custom: 'Custom',
    },
  },
  appointments: {
    slotMinutes: 'Slot interval (minutes)',
    minNotice: 'Minimum notice (hours)',
    bookingWindow: 'Booking window (days)',
    hoursHint: 'Opening hours are set in Business profile.',
    save: 'Save appointment settings',
  },
  designations: {
    add: 'Add designation',
    emptyTitle: 'No designations yet',
    name: 'Name',
    permissions: 'Permissions',
    deactivate: 'Deactivate',
    delete: 'Delete',
    edit: 'Edit',
    staffCount: 'Staff',
    unassigned: 'Unassigned',
    adminEntry: 'Admin',
    fullAccess: 'Full access',
    editTitle: 'Edit designation',
    createTitle: 'New designation',
    save: 'Save designation',
    unsaved: 'You have unsaved changes',
    selectAll: 'Select all',
    view: 'View',
    create: 'Create',
    editAction: 'Edit',
    deleteAction: 'Delete',
    maxDiscount: 'Maximum discount %',
    viewRevenue: 'View revenue and profit figures',
    exportData: 'Export data',
    adminOnly: 'Only admins can manage roles and permissions.',
    cannotDeleteAssigned: 'Reassign staff before deleting this designation.',
  },
  weekday: {
    monday: 'Mon',
    tuesday: 'Tue',
    wednesday: 'Wed',
    thursday: 'Thu',
    friday: 'Fri',
    saturday: 'Sat',
    sunday: 'Sun',
  },
  toasts: {
    businessSaved: 'Business profile saved',
    taxSaved: 'Tax settings saved',
    invoiceSaved: 'Invoice settings saved',
    appointmentsSaved: 'Appointment settings saved',
    loyaltySaved: 'Loyalty settings saved',
    logoUpdated: 'Logo updated',
    logoRemoved: 'Logo removed',
    hoursWarning: 'Some existing appointments fall outside the new hours.',
    designationCreated: 'Designation created',
    designationUpdated: 'Designation updated',
    designationDeleted: 'Designation deleted',
  },
} as const
