export const STAFF = {
  list: {
    description: 'Salon roster for appointments and billing.',
    add: 'Add staff',
    emptyTitle: 'No staff yet',
    emptyHint: 'Add stylists and front-desk team members.',
    searchPlaceholder: 'Search by name',
    loginEnabled: 'Login enabled',
    loginOff: 'Login off',
    mustChangePassword: 'Must change password',
    noLogin: 'No login',
  },
  detail: {
    description: 'Staff profile and login access.',
    edit: 'Edit staff',
    allowLogin: 'Allow login',
    username: 'Username',
    temporaryPassword: 'Temporary password',
    generatePassword: 'Generate',
    enableLogin: 'Enable login',
    resetPassword: 'Reset password',
    turnOffLogin: 'Turn off login',
    tempPasswordOnce: 'Copy this temporary password now. It will not be shown again.',
    copyPassword: 'Copy password',
    passwordStrength: 'Use at least 8 characters. Mix letters and numbers.',
  },
  form: {
    name: 'Name',
    age: 'Age',
    gender: 'Gender',
    designation: 'Designation',
    active: 'Active',
    allowLogin: 'Allow login',
    createTitle: 'Add staff',
    editTitle: 'Edit staff',
    noLoginHint: 'Turn on Allow login to create a username and temporary password.',
  },
  toasts: {
    created: 'Staff added',
    updated: 'Staff updated',
    deleted: 'Staff removed',
    loginEnabled: 'Login enabled',
    loginDisabled: 'Login turned off',
    passwordReset: 'Password reset',
    copied: 'Copied',
  },
} as const
